# Generated by Django 4.2.1 on 2023-07-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_arrivaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='arrivalTime',
            new_name='arrival_time',
        ),
    ]
