# Generated by Django 4.2.1 on 2023-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_arrivaltime_product_arrival_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='arrival_time',
            field=models.DateField(auto_now=True),
        ),
    ]
