# Generated by Django 4.2.1 on 2023-08-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity_in_cart',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
