# Generated by Django 4.2.1 on 2023-08-20 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_remove_cart_quantity_in_cart_alter_cartitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('HANDLING', 'Đang xử lý'), ('PACKING', 'Đang đóng gói'), ('SHIPPING', 'Đang gửi'), ('COMPLETED', 'Đã nhận hàng'), ('CANCELLED', 'Đã hủy')], default='HANDLING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
