# Generated by Django 4.2.1 on 2023-08-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
