# Generated by Django 4.2.1 on 2023-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='Người nhận', max_length=50),
            preserve_default=False,
        ),
    ]
