# Generated by Django 4.2.1 on 2023-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_receiver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='grand_total',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANKING', 'Thanh toán bằng tài khoản ngân hàng'), ('COD', 'Thanh toán khi nhận hàng')], default='COD', max_length=20),
        ),
    ]
