# Generated by Django 4.2.1 on 2023-08-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_payment_order_grand_total_order_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_code',
        ),
    ]
