# Generated by Django 4.2.1 on 2023-08-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_order_id_order_order_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://down-vn.img.susercontent.com/file/f2fbb47a0eed597ec1cac570c9ed7d5a', max_length=256),
            preserve_default=False,
        ),
    ]
