version: '3.9'
services:
  backend:
    image: thuanlee215/tecommerce:backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/app

  frontend:
    image: thuanlee215/tecommerce:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/app