version: '3.9'
services:
  backend:
    image: tecommerce-backend:lastest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/app
