version: '3.9'

services:
  backend:
      image: thuanlee215/tecommerce:backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8000:8000"

  frontend:
      image: thuanlee215/tecommerce:frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - shared_data:/app/build

  nginx:
    image: thuanlee215/tecommerce:nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - shared_data:/static
    depends_on:
      - backend

volumes:
  shared_data: